"""add_nse_refernce_tables

Revision ID: 09b769dd5c5c
Revises: a83e168c2cfa
Create Date: 2026-05-12 18:16:22.989605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09b769dd5c5c'
down_revision: Union[str, None] = 'a83e168c2cfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
