"""Delete column broker_id and add column source_id

Revision ID: 491e28677e29
Revises: aca419aa9b48
Create Date: 2026-02-24 20:36:28.633782

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "491e28677e29"
down_revision: Union[str, None] = "aca419aa9b48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_equity_data",
        sa.Column("source_id", sa.SmallInteger(), nullable=False, server_default="1"),
    )
    op.drop_constraint(
        "historical_equity_data_broker_id_fkey",
        "historical_equity_data",
        type_="foreignkey",
    )
    op.drop_column("historical_equity_data", "broker_id")
    op.add_column(
        "historical_index_data",
        sa.Column("source_id", sa.SmallInteger(), nullable=False, server_default="1"),
    )
    op.drop_constraint(
        "historical_index_data_broker_id_fkey",
        "historical_index_data",
        type_="foreignkey",
    )
    op.drop_column("historical_index_data", "broker_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "historical_index_data",
        sa.Column("broker_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "historical_index_data_broker_id_fkey",
        "historical_index_data",
        "broker",
        ["broker_id"],
        ["broker_id"],
    )
    op.drop_column("historical_index_data", "source_id")
    op.add_column(
        "historical_equity_data",
        sa.Column("broker_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "historical_equity_data_broker_id_fkey",
        "historical_equity_data",
        "broker",
        ["broker_id"],
        ["broker_id"],
    )
    op.drop_column("historical_equity_data", "source_id")
    # ### end Alembic commands ###
