"""missing_migration

Revision ID: 697f5b719477
Revises: 45f0b7f1da5f
Create Date: 2026-05-26 16:00:32.584879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697f5b719477'
down_revision: Union[str, None] = '45f0b7f1da5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('security_name', sa.String(length=200), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('buy_sell', sa.String(length=10), nullable=True),
    sa.Column('quantity_traded', sa.BigInteger(), nullable=True),
    sa.Column('trade_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'symbol', 'client_name', 'buy_sell', 'trade_price', 'quantity_traded', name='uq_block_deal')
    )
    op.create_index(op.f('ix_block_deals_client_name'), 'block_deals', ['client_name'], unique=False)
    op.create_index(op.f('ix_block_deals_date'), 'block_deals', ['date'], unique=False)
    op.create_index(op.f('ix_block_deals_symbol'), 'block_deals', ['symbol'], unique=False)
    op.create_table('bulk_deals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('security_name', sa.String(length=200), nullable=True),
    sa.Column('client_name', sa.String(length=200), nullable=True),
    sa.Column('buy_sell', sa.String(length=10), nullable=True),
    sa.Column('quantity_traded', sa.BigInteger(), nullable=True),
    sa.Column('trade_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'symbol', 'client_name', 'buy_sell', 'trade_price', 'quantity_traded', name='uq_bulk_deal')
    )
    op.create_index(op.f('ix_bulk_deals_client_name'), 'bulk_deals', ['client_name'], unique=False)
    op.create_index(op.f('ix_bulk_deals_date'), 'bulk_deals', ['date'], unique=False)
    op.create_index(op.f('ix_bulk_deals_symbol'), 'bulk_deals', ['symbol'], unique=False)
    op.create_table('fno_ban_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', 'symbol', name='uq_fno_ban_list_date_symbol')
    )
    op.create_index(op.f('ix_fno_ban_list_symbol'), 'fno_ban_list', ['symbol'], unique=False)
    op.create_index(op.f('ix_fno_ban_list_trade_date'), 'fno_ban_list', ['trade_date'], unique=False)
    op.add_column('fiidii_derivatives', sa.Column('net_volume', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('fiidii_derivatives', sa.Column('stock_net_volume', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('fiidii_derivatives', sa.Column('options_net_volume', sa.Numeric(precision=18, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fiidii_derivatives', 'options_net_volume')
    op.drop_column('fiidii_derivatives', 'stock_net_volume')
    op.drop_column('fiidii_derivatives', 'net_volume')
    op.drop_index(op.f('ix_fno_ban_list_trade_date'), table_name='fno_ban_list')
    op.drop_index(op.f('ix_fno_ban_list_symbol'), table_name='fno_ban_list')
    op.drop_table('fno_ban_list')
    op.drop_index(op.f('ix_bulk_deals_symbol'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_date'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_client_name'), table_name='bulk_deals')
    op.drop_table('bulk_deals')
    op.drop_index(op.f('ix_block_deals_symbol'), table_name='block_deals')
    op.drop_index(op.f('ix_block_deals_date'), table_name='block_deals')
    op.drop_index(op.f('ix_block_deals_client_name'), table_name='block_deals')
    op.drop_table('block_deals')
    # ### end Alembic commands ###
