"""add_prod_db_tables

Revision ID: 6af9cfb158c9
Revises: 697f5b719477
Create Date: 2026-05-27 12:54:26.562642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af9cfb158c9'
down_revision: Union[str, None] = '697f5b719477'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_data',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('traded_qty', sa.BigInteger(), nullable=False),
    sa.Column('deliverable_qty', sa.BigInteger(), nullable=False),
    sa.Column('delivery_pct', sa.Numeric(precision=6, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_table('futures_oi',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('open_interest', sa.BigInteger(), nullable=False),
    sa.Column('change_in_oi', sa.BigInteger(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('close', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'expiry_date')
    )
    op.create_table('india_vix',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('low', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('close', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('prev_close', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.PrimaryKeyConstraint('timestamp')
    )
    op.create_table('participant_oi',
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('futures_idx_long', sa.BigInteger(), nullable=True),
    sa.Column('futures_idx_short', sa.BigInteger(), nullable=True),
    sa.Column('futures_idx_net', sa.BigInteger(), nullable=True),
    sa.Column('futures_idx_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('futures_stk_long', sa.BigInteger(), nullable=True),
    sa.Column('futures_stk_short', sa.BigInteger(), nullable=True),
    sa.Column('futures_stk_net', sa.BigInteger(), nullable=True),
    sa.Column('futures_stk_outstanding', sa.BigInteger(), nullable=True),
    sa.Column('option_call_long_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_call_long_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_call_short_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_call_short_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_call_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_call_net_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_put_long_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_put_long_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_put_short_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_put_short_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_put_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_put_net_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('option_overall_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('option_overall_net_oi_change', sa.BigInteger(), nullable=True),
    sa.Column('nifty_fut_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('banknifty_fut_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('finnifty_fut_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('midcpnifty_fut_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('niftynxt50_fut_net_oi', sa.BigInteger(), nullable=True),
    sa.Column('futures_net_view', sa.String(length=20), nullable=True),
    sa.Column('futures_net_action', sa.String(length=20), nullable=True),
    sa.Column('futures_stk_net_view', sa.String(length=20), nullable=True),
    sa.Column('futures_stk_net_action', sa.String(length=20), nullable=True),
    sa.Column('options_net_view', sa.String(length=20), nullable=True),
    sa.Column('options_net_action', sa.String(length=20), nullable=True),
    sa.Column('nifty_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('banknifty_close', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('trade_date', 'category', 'source')
    )
    op.create_table('regime_log',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('predicted_state', sa.Integer(), nullable=False),
    sa.Column('state_probability', postgresql.ARRAY(sa.DOUBLE_PRECISION()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_table('watchlist_focus',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('xgboost_prob', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('technical_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol')
    )
    op.create_table('recommendation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('asset_class', sa.String(length=20), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('option_type', sa.String(length=10), nullable=True),
    sa.Column('strike_price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('entry_price_range', sa.String(length=100), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('execution_signal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_signal_id'], ['trading_signal.signal_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_symbol'), 'recommendation', ['symbol'], unique=False)
    op.create_index(op.f('ix_recommendation_timestamp'), 'recommendation', ['timestamp'], unique=False)
    op.drop_table('fiidii_derivatives')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fiidii_derivatives',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('instrument_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('net_oi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('outstanding_oi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('net_action', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('net_view', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('net_view_strength', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stock_net_oi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock_outstanding_oi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock_net_action', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stock_net_view', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('stock_net_view_strength', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('options_net_oi', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('options_net_oi_change', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('options_net_oi_change_action', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('options_net_oi_change_view', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('options_net_oi_change_view_strength', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('nifty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('nifty_change_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('banknifty', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('banknifty_change_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('extras', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('net_volume', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('stock_net_volume', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.Column('options_net_volume', sa.NUMERIC(precision=18, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fiidii_derivatives_pkey')),
    sa.UniqueConstraint('trade_date', 'source', 'category', 'instrument_type', name=op.f('fiidii_deriv_date_src_cat_inst_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_index(op.f('ix_recommendation_timestamp'), table_name='recommendation')
    op.drop_index(op.f('ix_recommendation_symbol'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_table('watchlist_focus')
    op.drop_table('regime_log')
    op.drop_table('participant_oi')
    op.drop_table('india_vix')
    op.drop_table('futures_oi')
    op.drop_table('delivery_data')
    # ### end Alembic commands ###
