"""add_corporate_announcement

Revision ID: 73cd3098b8b9
Revises: b2bcd654344c
Create Date: 2026-06-09 06:09:54.681370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73cd3098b8b9'
down_revision: Union[str, None] = 'b2bcd654344c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_announcement',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('seq_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('subject', sa.Text(), nullable=True),
    sa.Column('announcement_text', sa.Text(), nullable=True),
    sa.Column('announcement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attachment_url', sa.String(length=500), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq_id', name='uq_corporate_announcement_seq_id')
    )
    op.create_index(op.f('ix_corporate_announcement_announcement_date'), 'corporate_announcement', ['announcement_date'], unique=False)
    op.create_index(op.f('ix_corporate_announcement_seq_id'), 'corporate_announcement', ['seq_id'], unique=True)
    op.create_index(op.f('ix_corporate_announcement_symbol'), 'corporate_announcement', ['symbol'], unique=False)
    op.add_column('trade', sa.Column('stop_loss', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trade', sa.Column('target', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trade', sa.Column('net_pnl', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('trade', sa.Column('exit_reason', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'exit_reason')
    op.drop_column('trade', 'net_pnl')
    op.drop_column('trade', 'target')
    op.drop_column('trade', 'stop_loss')
    op.drop_index(op.f('ix_corporate_announcement_symbol'), table_name='corporate_announcement')
    op.drop_index(op.f('ix_corporate_announcement_seq_id'), table_name='corporate_announcement')
    op.drop_index(op.f('ix_corporate_announcement_announcement_date'), table_name='corporate_announcement')
    op.drop_table('corporate_announcement')
    # ### end Alembic commands ###
