"""Add server default for celery task log

Revision ID: 7990121e09cb
Revises: c86ea6ec0453
Create Date: 2026-05-14 23:20:10.104266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7990121e09cb'
down_revision: Union[str, None] = 'c86ea6ec0453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
