"""signal_related_updates

Revision ID: 7b33c39a22c5
Revises: 73cd3098b8b9
Create Date: 2026-06-11 06:16:57.161185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b33c39a22c5'
down_revision: Union[str, None] = '73cd3098b8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('macro_indicator',
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('indicator_type', sa.String(length=20), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.Column('open', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('high', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('low', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('prev_close', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('change', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('pct_change', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol'),
    sa.UniqueConstraint('timestamp', 'symbol', name='uq_macro_indicator_ts_sym')
    )
    op.add_column('trading_signal', sa.Column('instrument_type', sa.String(length=10), nullable=True))
    op.add_column('trading_signal', sa.Column('strategy_type', sa.String(length=40), nullable=True))
    op.add_column('trading_signal', sa.Column('strike_price', sa.Numeric(precision=14, scale=2), nullable=True))
    op.add_column('trading_signal', sa.Column('expiry_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trading_signal', 'expiry_date')
    op.drop_column('trading_signal', 'strike_price')
    op.drop_column('trading_signal', 'strategy_type')
    op.drop_column('trading_signal', 'instrument_type')
    op.drop_table('macro_indicator')
    # ### end Alembic commands ###
