"""add_fundamental_data_tables

Revision ID: 8229aa0a10ef
Revises: 0d74251f71ff
Create Date: 2026-03-16 18:21:09.835973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8229aa0a10ef'
down_revision: Union[str, None] = '0d74251f71ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('derivative_tick',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('contract_type', sa.String(length=10), nullable=False),
    sa.Column('strike', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expiry', sa.Date(), nullable=False),
    sa.Column('price', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('bid', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ask', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('implied_vol', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('timestamp', 'symbol', 'contract_type', 'strike', 'expiry', name='uq_deriv_tick_ts_sym_typ_strk_exp')
    )
    op.create_index(op.f('ix_derivative_tick_expiry'), 'derivative_tick', ['expiry'], unique=False)
    op.create_index(op.f('ix_derivative_tick_symbol'), 'derivative_tick', ['symbol'], unique=False)
    op.create_index(op.f('ix_derivative_tick_timestamp'), 'derivative_tick', ['timestamp'], unique=False)
    op.create_table('fundamental_data',
    sa.Column('fundamental_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('beta', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roe', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('report_xml', sa.Text(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('fundamental_id'),
    sa.UniqueConstraint('symbol', name='uq_fundamental_data_symbol')
    )
    op.create_index(op.f('ix_fundamental_data_instrument_id'), 'fundamental_data', ['instrument_id'], unique=False)
    op.create_index(op.f('ix_fundamental_data_symbol'), 'fundamental_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fundamental_data_symbol'), table_name='fundamental_data')
    op.drop_index(op.f('ix_fundamental_data_instrument_id'), table_name='fundamental_data')
    op.drop_table('fundamental_data')
    op.drop_index(op.f('ix_derivative_tick_timestamp'), table_name='derivative_tick')
    op.drop_index(op.f('ix_derivative_tick_symbol'), table_name='derivative_tick')
    op.drop_index(op.f('ix_derivative_tick_expiry'), table_name='derivative_tick')
    op.drop_table('derivative_tick')
    # ### end Alembic commands ###
