"""Generate table for nse-reference

Revision ID: 86bf9d716cdd
Revises: b4d92e27965c
Create Date: 2026-05-12 18:53:48.115882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86bf9d716cdd'
down_revision: Union[str, None] = 'b4d92e27965c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fno_expiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('instrument_type', sa.String(length=20), nullable=False),
    sa.Column('underlying_symbol', sa.String(length=50), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('instrument_type', 'underlying_symbol', 'expiry_date', name='uix_fno_expiry_type_sym_date')
    )
    op.create_table('index_constituent',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_category', sa.String(length=50), nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('series', sa.String(length=10), nullable=True),
    sa.Column('as_of_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name', 'symbol', name='uix_index_constituent_idx_sym')
    )
    op.create_table('nse_index',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False),
    sa.Column('index_symbol', sa.String(length=50), nullable=False),
    sa.Column('constituent_url', sa.String(length=255), nullable=True),
    sa.Column('factsheet_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category', 'index_name', name='uix_nse_index_cat_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nse_index')
    op.drop_table('index_constituent')
    op.drop_table('fno_expiry')
    # ### end Alembic commands ###
