"""update_instruments_model

Revision ID: 8ec9a1295d43
Revises: 491e28677e29
Create Date: 2026-02-25 14:12:13.476131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8ec9a1295d43'
down_revision: Union[str, None] = '491e28677e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('symbol', sa.String(length=100), nullable=True))
    op.add_column('instrument', sa.Column('sector', sa.String(length=200), nullable=True))
    op.add_column('instrument', sa.Column('is_nifty_50', sa.SmallInteger(), nullable=True, server_default='0'))
    op.add_column('instrument', sa.Column('is_nifty_100', sa.SmallInteger(), nullable=True, server_default='0'))
    op.add_column('instrument', sa.Column('is_nifty_500', sa.SmallInteger(), nullable=True, server_default='0'))
    op.alter_column('instrument', 'isin',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('instrument', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.create_index(op.f('ix_instrument_symbol'), 'instrument', ['symbol'], unique=False)
    op.drop_column('instrument', 'icici_symbol')
    op.drop_column('instrument', 'indices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument', sa.Column('indices', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('instrument', sa.Column('icici_symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_instrument_symbol'), table_name='instrument')
    op.alter_column('instrument', 'company_name',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('instrument', 'isin',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('instrument', 'is_nifty_500')
    op.drop_column('instrument', 'is_nifty_100')
    op.drop_column('instrument', 'is_nifty_50')
    op.drop_column('instrument', 'sector')
    op.drop_column('instrument', 'symbol')
    # ### end Alembic commands ###
