"""add_column_shares_traded_turnover_for_index

Revision ID: a83e168c2cfa
Revises: 8229aa0a10ef
Create Date: 2026-03-19 13:44:06.941162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a83e168c2cfa'
down_revision: Union[str, None] = '8229aa0a10ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('historical_index_data', sa.Column('shares_traded', sa.BigInteger(), nullable=True))
    op.add_column('historical_index_data', sa.Column('turnover_cr', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('historical_index_data', 'turnover_cr')
    op.drop_column('historical_index_data', 'shares_traded')
    # ### end Alembic commands ###
