"""Initialise tables

Revision ID: aca419aa9b48
Revises: 
Create Date: 2026-02-24 16:27:10.429308

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aca419aa9b48"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "broker",
        sa.Column("broker_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("broker_name", sa.String(length=20), nullable=False),
        sa.Column("broker_type", sa.String(length=20), nullable=True),
        sa.Column("is_active", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("broker_id"),
        sa.UniqueConstraint("broker_name"),
    )
    op.create_table(
        "candle",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("vwap", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("ts", "symbol", "timeframe"),
    )
    op.create_table(
        "corporate_event",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column(
            "event_type",
            postgresql.ENUM(
                "RESULT",
                "DIVIDEND",
                "AGM",
                "BONUS",
                "SPLIT",
                "BUYBACK",
                "RIGHTS",
                "OTHER",
                name="event_type",
            ),
            nullable=False,
        ),
        sa.Column("event_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ex_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("record_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("subject", sa.Text(), nullable=True),
        sa.Column("isin", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("symbol", "event_date", name="uix_corporate_event_key"),
    )
    op.create_index(
        op.f("ix_corporate_event_event_date"),
        "corporate_event",
        ["event_date"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_event_event_type"),
        "corporate_event",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_corporate_event_symbol"), "corporate_event", ["symbol"], unique=False
    )
    op.create_table(
        "external_api_request",
        sa.Column("request_id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("api_provider", sa.Integer(), nullable=False),
        sa.Column("api_endpoint", sa.String(length=500), nullable=False),
        sa.Column("http_method", sa.String(length=10), nullable=False),
        sa.Column("request_headers", sa.Text(), nullable=True),
        sa.Column("request_payload", sa.Text(), nullable=True),
        sa.Column("http_status_code", sa.Integer(), nullable=True),
        sa.Column("response_headers", sa.Text(), nullable=True),
        sa.Column("response_payload", sa.Text(), nullable=True),
        sa.Column("request_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("response_timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("is_success", sa.SmallInteger(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=True),
        sa.Column("circuit_breaker_state", sa.Integer(), nullable=True),
        sa.Column("correlation_id", sa.String(length=36), nullable=True),
        sa.Column("user_agent", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("request_id"),
    )
    op.create_index(
        op.f("ix_external_api_request_api_provider"),
        "external_api_request",
        ["api_provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_request_correlation_id"),
        "external_api_request",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_request_http_status_code"),
        "external_api_request",
        ["http_status_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_request_is_success"),
        "external_api_request",
        ["is_success"],
        unique=False,
    )
    op.create_index(
        op.f("ix_external_api_request_request_timestamp"),
        "external_api_request",
        ["request_timestamp"],
        unique=False,
    )
    op.create_table(
        "fiidii",
        sa.Column("fiidii_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("category", sa.String(length=10), nullable=False),
        sa.Column("segment", sa.String(length=20), nullable=False),
        sa.Column("buy_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("sell_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("net_value", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("fiidii_id"),
        sa.UniqueConstraint(
            "trade_date",
            "category",
            "segment",
            name="fiidii_trade_date_category_segment_key",
        ),
    )
    op.create_table(
        "instrument",
        sa.Column("instrument_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("isin", sa.String(length=20), nullable=False),
        sa.Column("ib_symbol", sa.String(length=20), nullable=False),
        sa.Column("icici_symbol", sa.String(length=20), nullable=True),
        sa.Column("company_name", sa.String(length=255), nullable=True),
        sa.Column("is_fno", sa.SmallInteger(), nullable=True),
        sa.Column("indices", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("is_index", sa.SmallInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("instrument_id"),
    )
    op.create_index(
        op.f("ix_instrument_ib_symbol"), "instrument", ["ib_symbol"], unique=False
    )
    op.create_index(op.f("ix_instrument_isin"), "instrument", ["isin"], unique=True)
    op.create_table(
        "market_breadth",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("advances", sa.Integer(), nullable=False),
        sa.Column("declines", sa.Integer(), nullable=False),
        sa.Column("unchanged", sa.Integer(), nullable=False),
        sa.Column("advance_volume", sa.BigInteger(), nullable=True),
        sa.Column("decline_volume", sa.BigInteger(), nullable=True),
        sa.Column("ad_ratio", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.PrimaryKeyConstraint("ts", "exchange"),
    )
    op.create_table(
        "news",
        sa.Column("news_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=True),
        sa.Column("symbols", sa.String(length=200), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("news_id"),
    )
    op.create_index(
        op.f("ix_news_published_at"), "news", ["published_at"], unique=False
    )
    op.create_index(op.f("ix_news_source"), "news", ["source"], unique=False)
    op.create_table(
        "option_chain",
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol", sa.String(length=30), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.Column("strike_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("option_type", sa.String(length=2), nullable=False),
        sa.Column("open", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("high", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("low", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("close", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("ltp", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=True),
        sa.Column("open_interest", sa.BigInteger(), nullable=True),
        sa.Column("change_in_oi", sa.BigInteger(), nullable=True),
        sa.Column("implied_vol", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("delta", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("gamma", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("theta", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("vega", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("bid_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("ask_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("bid_qty", sa.Integer(), nullable=True),
        sa.Column("ask_qty", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint(
            "ts", "symbol", "expiry_date", "strike_price", "option_type"
        ),
    )
    op.create_table(
        "system_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("service", sa.String(length=50), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_log_ts"), "system_log", ["ts"], unique=False)
    op.create_table(
        "system_metric",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_equity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("cash_balance", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("peak_equity", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("drawdown_pct", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column("open_positions", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_system_metric_timestamp"), "system_metric", ["timestamp"], unique=False
    )
    op.create_table(
        "trading_holiday",
        sa.Column("holiday_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("holiday_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("holiday_name", sa.String(length=200), nullable=False),
        sa.Column("holiday_type", sa.String(length=50), nullable=True),
        sa.Column("week_day", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("holiday_id"),
    )
    op.create_index(
        op.f("ix_trading_holiday_holiday_date"),
        "trading_holiday",
        ["holiday_date"],
        unique=True,
    )
    op.create_table(
        "broker_health_log",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=True),
        sa.Column("layer", sa.String(length=10), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "historical_equity_data",
        sa.Column(
            "historical_equity_data_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("volume", sa.BigInteger(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("historical_equity_data_id"),
        sa.UniqueConstraint(
            "symbol", "timeframe", "timestamp", name="uix_historical_data_key"
        ),
    )
    op.create_index(
        op.f("ix_historical_equity_data_symbol"),
        "historical_equity_data",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_equity_data_timeframe"),
        "historical_equity_data",
        ["timeframe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_equity_data_timestamp"),
        "historical_equity_data",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "historical_index_data",
        sa.Column(
            "historical_index_data_id",
            sa.BigInteger(),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("timeframe", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("index_name", sa.String(length=20), nullable=False),
        sa.Column("open", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("high", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("low", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("close", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("adj_close", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("broker_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("historical_index_data_id"),
        sa.UniqueConstraint(
            "symbol",
            "timeframe",
            "timestamp",
            "index_name",
            name="uix_historical_index_data_key",
        ),
    )
    op.create_index(
        op.f("ix_historical_index_data_index_name"),
        "historical_index_data",
        ["index_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_index_data_symbol"),
        "historical_index_data",
        ["symbol"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_index_data_timeframe"),
        "historical_index_data",
        ["timeframe"],
        unique=False,
    )
    op.create_index(
        op.f("ix_historical_index_data_timestamp"),
        "historical_index_data",
        ["timestamp"],
        unique=False,
    )
    op.create_table(
        "position",
        sa.Column("position_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column("net_quantity", sa.Integer(), nullable=False),
        sa.Column("average_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("unrealized_pnl", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("position_id"),
        sa.UniqueConstraint("instrument_id", "broker_id", name="uix_position_key"),
    )
    op.create_index(
        op.f("ix_position_broker_id"), "position", ["broker_id"], unique=False
    )
    op.create_index(
        op.f("ix_position_instrument_id"), "position", ["instrument_id"], unique=False
    )
    op.create_table(
        "trading_order",
        sa.Column("order_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("strategy_id", sa.String(length=50), nullable=True),
        sa.Column("broker_order_id", sa.String(length=50), nullable=True),
        sa.Column("broker_id", sa.Integer(), nullable=True),
        sa.Column("symbol", sa.String(length=20), nullable=True),
        sa.Column(
            "side",
            postgresql.ENUM("BUY", "SELL", "HOLD", name="order_side"),
            nullable=False,
        ),
        sa.Column(
            "order_type",
            postgresql.ENUM(
                "MKT", "LMT", "STP", "STP_LMT", "BRACKET", "TRAIL", name="order_type"
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("limit_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("stop_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("trail_stop_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "NEW",
                "PENDING",
                "PARTIALLY_FILLED",
                "FILLED",
                "CANCELLED",
                "REJECTED",
                name="order_status",
            ),
            nullable=False,
        ),
        sa.Column("filled_quantity", sa.Integer(), nullable=True),
        sa.Column("avg_fill_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("commission", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("parent_order_id", sa.Integer(), nullable=True),
        sa.Column("filled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_order_id"],
            ["trading_order.order_id"],
        ),
        sa.PrimaryKeyConstraint("order_id"),
        sa.UniqueConstraint("broker_order_id"),
    )
    op.create_table(
        "trading_signal",
        sa.Column("signal_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("instrument_id", sa.Integer(), nullable=True),
        sa.Column("strategy_name", sa.String(length=100), nullable=False),
        sa.Column(
            "action",
            postgresql.ENUM("BUY", "SELL", "EXIT", name="signal_action"),
            nullable=False,
        ),
        sa.Column(
            "timeframe",
            postgresql.ENUM(
                "SCALPING", "INTRADAY", "SWING", "POSITIONAL", name="signal_timeframe"
            ),
            nullable=False,
        ),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("target_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("stop_loss", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=4, scale=3), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("indicators", sa.JSON(), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column("is_executed", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("signal_id"),
    )
    op.create_table(
        "trade",
        sa.Column("trade_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("strategy_id", sa.String(length=50), nullable=True),
        sa.Column("instrument_id", sa.Integer(), nullable=False),
        sa.Column("broker_id", sa.Integer(), nullable=False),
        sa.Column("entry_order_id", sa.Integer(), nullable=True),
        sa.Column("exit_order_id", sa.Integer(), nullable=True),
        sa.Column(
            "side",
            postgresql.ENUM("BUY", "SELL", "HOLD", name="order_side"),
            nullable=False,
        ),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("exit_price", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("commission", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("slippage", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("OPEN", "CLOSED", name="trade_status"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["broker_id"],
            ["broker.broker_id"],
        ),
        sa.ForeignKeyConstraint(
            ["entry_order_id"],
            ["trading_order.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["exit_order_id"],
            ["trading_order.order_id"],
        ),
        sa.ForeignKeyConstraint(
            ["instrument_id"],
            ["instrument.instrument_id"],
        ),
        sa.PrimaryKeyConstraint("trade_id"),
    )
    op.create_index(op.f("ix_trade_broker_id"), "trade", ["broker_id"], unique=False)
    op.create_index(op.f("ix_trade_status"), "trade", ["status"], unique=False)
    op.create_index(
        op.f("ix_trade_strategy_id"), "trade", ["strategy_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_strategy_id"), table_name="trade")
    op.drop_index(op.f("ix_trade_status"), table_name="trade")
    op.drop_index(op.f("ix_trade_broker_id"), table_name="trade")
    op.drop_table("trade")
    op.drop_table("trading_signal")
    op.drop_table("trading_order")
    op.drop_index(op.f("ix_position_instrument_id"), table_name="position")
    op.drop_index(op.f("ix_position_broker_id"), table_name="position")
    op.drop_table("position")
    op.drop_index(
        op.f("ix_historical_index_data_timestamp"), table_name="historical_index_data"
    )
    op.drop_index(
        op.f("ix_historical_index_data_timeframe"), table_name="historical_index_data"
    )
    op.drop_index(
        op.f("ix_historical_index_data_symbol"), table_name="historical_index_data"
    )
    op.drop_index(
        op.f("ix_historical_index_data_index_name"), table_name="historical_index_data"
    )
    op.drop_table("historical_index_data")
    op.drop_index(
        op.f("ix_historical_equity_data_timestamp"), table_name="historical_equity_data"
    )
    op.drop_index(
        op.f("ix_historical_equity_data_timeframe"), table_name="historical_equity_data"
    )
    op.drop_index(
        op.f("ix_historical_equity_data_symbol"), table_name="historical_equity_data"
    )
    op.drop_table("historical_equity_data")
    op.drop_table("broker_health_log")
    op.drop_index(op.f("ix_trading_holiday_holiday_date"), table_name="trading_holiday")
    op.drop_table("trading_holiday")
    op.drop_index(op.f("ix_system_metric_timestamp"), table_name="system_metric")
    op.drop_table("system_metric")
    op.drop_index(op.f("ix_system_log_ts"), table_name="system_log")
    op.drop_table("system_log")
    op.drop_table("option_chain")
    op.drop_index(op.f("ix_news_source"), table_name="news")
    op.drop_index(op.f("ix_news_published_at"), table_name="news")
    op.drop_table("news")
    op.drop_table("market_breadth")
    op.drop_index(op.f("ix_instrument_isin"), table_name="instrument")
    op.drop_index(op.f("ix_instrument_ib_symbol"), table_name="instrument")
    op.drop_table("instrument")
    op.drop_table("fiidii")
    op.drop_index(
        op.f("ix_external_api_request_request_timestamp"),
        table_name="external_api_request",
    )
    op.drop_index(
        op.f("ix_external_api_request_is_success"), table_name="external_api_request"
    )
    op.drop_index(
        op.f("ix_external_api_request_http_status_code"),
        table_name="external_api_request",
    )
    op.drop_index(
        op.f("ix_external_api_request_correlation_id"),
        table_name="external_api_request",
    )
    op.drop_index(
        op.f("ix_external_api_request_api_provider"), table_name="external_api_request"
    )
    op.drop_table("external_api_request")
    op.drop_index(op.f("ix_corporate_event_symbol"), table_name="corporate_event")
    op.drop_index(op.f("ix_corporate_event_event_type"), table_name="corporate_event")
    op.drop_index(op.f("ix_corporate_event_event_date"), table_name="corporate_event")
    op.drop_table("corporate_event")
    op.drop_table("candle")
    op.drop_table("broker")
    # ### end Alembic commands ###
