"""add_purpose_to_events

Revision ID: b4d92e27965c
Revises: 09b769dd5c5c
Create Date: 2026-05-12 18:33:49.480058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4d92e27965c'
down_revision: Union[str, None] = '09b769dd5c5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_event', sa.Column('purpose', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporate_event', 'purpose')
    # ### end Alembic commands ###
