"""Add underlying vakue to option chain

Revision ID: c86ea6ec0453
Revises: e7748d9b24be
Create Date: 2026-05-14 22:13:34.696037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86ea6ec0453'
down_revision: Union[str, None] = 'e7748d9b24be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('option_chain', sa.Column('underlying_value', sa.Numeric(precision=14, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('option_chain', 'underlying_value')
    # ### end Alembic commands ###
