"""Generate table for celery task logs

Revision ID: e7748d9b24be
Revises: 86bf9d716cdd
Create Date: 2026-05-14 13:52:44.294362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7748d9b24be'
down_revision: Union[str, None] = '86bf9d716cdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('celery_task_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_celery_task_logs_id'), 'celery_task_logs', ['id'], unique=False)
    op.create_index(op.f('ix_celery_task_logs_task_id'), 'celery_task_logs', ['task_id'], unique=True)
    op.drop_column('corporate_event', 'subject')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_event', sa.Column('subject', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_celery_task_logs_task_id'), table_name='celery_task_logs')
    op.drop_index(op.f('ix_celery_task_logs_id'), table_name='celery_task_logs')
    op.drop_table('celery_task_logs')
    # ### end Alembic commands ###
