"""add_news_full_text_and_sentiment

Revision ID: ee6367c36683
Revises: 7b33c39a22c5
Create Date: 2026-07-01 06:57:16.812438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee6367c36683'
down_revision: Union[str, None] = '7b33c39a22c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_sentiment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('announcement_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('sentiment_direction', sa.SmallInteger(), nullable=True),
    sa.Column('sentiment_magnitude', sa.String(length=10), nullable=True),
    sa.Column('sentiment_horizon', sa.String(length=10), nullable=True),
    sa.Column('sentiment_is_material', sa.Boolean(), nullable=True),
    sa.Column('sentiment_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('sentiment_reasoning', sa.Text(), nullable=True),
    sa.Column('sentiment_model', sa.String(length=50), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['announcement_id'], ['corporate_announcement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corporate_sentiment_scored_at'), 'corporate_sentiment', ['scored_at'], unique=False)
    op.create_index(op.f('ix_corporate_sentiment_symbol'), 'corporate_sentiment', ['symbol'], unique=False)
    # uq_macro_indicator_ts_sym already exists in DB, skipping recreate
    op.add_column('news', sa.Column('full_text', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('full_text_status', sa.String(length=20), nullable=True))
    op.add_column('news', sa.Column('full_text_fetched_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news', sa.Column('sentiment_direction', sa.SmallInteger(), nullable=True))
    op.add_column('news', sa.Column('sentiment_magnitude', sa.String(length=10), nullable=True))
    op.add_column('news', sa.Column('sentiment_horizon', sa.String(length=10), nullable=True))
    op.add_column('news', sa.Column('sentiment_is_material', sa.Boolean(), nullable=True))
    op.add_column('news', sa.Column('sentiment_confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.add_column('news', sa.Column('sentiment_score', sa.Numeric(precision=6, scale=4), nullable=True))
    op.add_column('news', sa.Column('sentiment_reasoning', sa.Text(), nullable=True))
    op.add_column('news', sa.Column('sentiment_scored_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('news', sa.Column('sentiment_model', sa.String(length=50), nullable=True))
    op.add_column('news', sa.Column('sentiment_input', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news', 'sentiment_input')
    op.drop_column('news', 'sentiment_model')
    op.drop_column('news', 'sentiment_scored_at')
    op.drop_column('news', 'sentiment_reasoning')
    op.drop_column('news', 'sentiment_score')
    op.drop_column('news', 'sentiment_confidence')
    op.drop_column('news', 'sentiment_is_material')
    op.drop_column('news', 'sentiment_horizon')
    op.drop_column('news', 'sentiment_magnitude')
    op.drop_column('news', 'sentiment_direction')
    op.drop_column('news', 'full_text_fetched_at')
    op.drop_column('news', 'full_text_status')
    op.drop_column('news', 'full_text')
    op.drop_index(op.f('ix_corporate_sentiment_symbol'), table_name='corporate_sentiment')
    op.drop_index(op.f('ix_corporate_sentiment_scored_at'), table_name='corporate_sentiment')
    op.drop_table('corporate_sentiment')
    # ### end Alembic commands ###
