"""Trading Bot Utilities Library (tb_utils).

A comprehensive library for algorithmic trading with utilities for
PostgreSQL/TimescaleDB data handling, SQLAlchemy model management,
Pydantic schema validation, and external API integration.
"""

__version__ = "1.7.1"

from .config.database import DatabaseConfig, db_settings
from .config.db_session import SessionLocal, get_db
from .models import (
    Base,
    BlockDeal,
    Broker,
    BrokerHealthLog,
    BulkDeal,
    Candle,
    CorporateEvent,
    DeliveryData,
    DerivativeTick,
    ExternalApiRequest,
    FiiDii,
    FnoExpiry,
    FundamentalData,
    FuturesOI,
    HistoricalEquityData,
    HistoricalIndexData,
    IndexConstituent,
    IndiaVIX,
    Instrument,
    MarketBreadth,
    News,
    NseIndex,
    OptionChain,
    ParticipantOI,
    Position,
    Recommendation,
    RegimeLog,
    SystemLog,
    SystemMetric,
    Trade,
    TradingHoliday,
    TradingOrder,
    TradingSignal,
    WatchlistFocus,
)
from .request_maker import CircuitBreakerError, RequestMaker
from .schema import (
    BrokerHealthLogResponse,
    BrokerResponse,
    CandleResponse,
    CorporateEventResponse,
    DeliveryDataResponse,
    ExternalApiRequestCreate,
    ExternalApiRequestResponse,
    FiiDiiResponse,
    FuturesOIResponse,
    GenericResponseSchema,
    HistoricalEquityDataResponse,
    HistoricalIndexDataResponse,
    IndiaVIXResponse,
    InstrumentResponse,
    MarketBreadthResponse,
    NewsResponse,
    OptionChainResponse,
    ParticipantOIResponse,
    PositionResponse,
    RecommendationCreate,
    RecommendationResponse,
    RegimeLogResponse,
    SystemLogResponse,
    SystemMetricResponse,
    TradeResponse,
    TradingHolidayResponse,
    TradingOrderCreate,
    TradingOrderResponse,
    TradingSignalCreate,
    TradingSignalResponse,
    WatchlistFocusResponse,
)

__all__ = [
    # Version
    "__version__",
    # Config
    "DatabaseConfig",
    "db_settings",
    "SessionLocal",
    "get_db",
    # Models
    "Base",
    "BlockDeal",
    "Broker",
    "BrokerHealthLog",
    "BulkDeal",
    "Candle",
    "CorporateEvent",
    "DerivativeTick",
    "ExternalApiRequest",
    "FiiDii",
    "FnoExpiry",
    "FundamentalData",
    "HistoricalEquityData",
    "HistoricalIndexData",
    "IndexConstituent",
    "Instrument",
    "MarketBreadth",
    "News",
    "NseIndex",
    "OptionChain",
    "Position",
    "SystemLog",
    "SystemMetric",
    "Trade",
    "TradingHoliday",
    "TradingOrder",
    "TradingSignal",
    "IndiaVIX",
    "FuturesOI",
    "ParticipantOI",
    "DeliveryData",
    "RegimeLog",
    "WatchlistFocus",
    "Recommendation",
    # Schemas
    "GenericResponseSchema",
    "BrokerResponse",
    "BrokerHealthLogResponse",
    "ExternalApiRequestCreate",
    "ExternalApiRequestResponse",
    "CorporateEventResponse",
    "TradingHolidayResponse",
    "HistoricalEquityDataResponse",
    "HistoricalIndexDataResponse",
    "CandleResponse",
    "OptionChainResponse",
    "InstrumentResponse",
    "FiiDiiResponse",
    "MarketBreadthResponse",
    "NewsResponse",
    "SystemMetricResponse",
    "SystemLogResponse",
    "TradingSignalCreate",
    "TradingSignalResponse",
    "TradingOrderCreate",
    "TradingOrderResponse",
    "PositionResponse",
    "TradeResponse",
    "IndiaVIXResponse",
    "FuturesOIResponse",
    "ParticipantOIResponse",
    "DeliveryDataResponse",
    "RegimeLogResponse",
    "WatchlistFocusResponse",
    "RecommendationCreate",
    "RecommendationResponse",
    # Request Maker
    "RequestMaker",
    "CircuitBreakerError",
]
