"""Trading Bot Utilities Library (tb_utils).

A comprehensive library for algorithmic trading with utilities for
PostgreSQL/TimescaleDB data handling, SQLAlchemy model management,
Pydantic schema validation, and external API integration.
"""

__version__ = "1.16.9"

from .broker.base import (
    BrokerAdapter,
    OrderRequest,
    OrderResult,
    OrderSide,
    OrderStatus,
    OrderType,
    PortfolioPosition,
    TimeInForce,
)
from .calendar import get_trading_holidays_for_year, is_trading_holiday
from .config.apiconfig import UpstoxApiConfig
from .config.database import DatabaseConfig, db_settings
from .config.db_session import SessionLocal, get_db
from .errors import CircuitOpen, DataUnavailable, ExternalApiError, NxTradeError
from .greeks import (
    GreeksResult,
    calculate_greeks,
    calculate_iv_percentile,
    calculate_iv_rank,
)
from .models import (
    Base,
    BlockDeal,
    Broker,
    BrokerHealthLog,
    BulkDeal,
    Candle,
    CorporateEvent,
    DeliveryData,
    DerivativeTick,
    ExternalApiRequest,
    FiiDii,
    FnoExpiry,
    FundamentalData,
    FundamentalUniverse,
    FuturesOI,
    HistoricalEquityData,
    HistoricalIndexData,
    IndexConstituent,
    IndiaVIX,
    Instrument,
    MarketBreadth,
    News,
    NseIndex,
    OptionChain,
    OptionDailyMetrics,
    OptionStrategyLeg,
    OptionStrategySignal,
    ParticipantOI,
    Position,
    RegimeLog,
    SystemLog,
    SystemMetric,
    Trade,
    TradingHoliday,
    TradingOrder,
    TradingSignal,
    WatchlistFocus,
)
from .options import ResolvedContract, resolve_option_contract
from .request_maker import CircuitBreakerError, RequestMaker
from .risk import ATR_STOP_MULTIPLIER, REGIME_RULES
from .schema import (
    BlockDealResponse,
    BrokerHealthLogResponse,
    BrokerResponse,
    BulkDealResponse,
    CandleResponse,
    CorporateEventResponse,
    DeliveryDataResponse,
    DerivativeMetricsResponse,
    DerivativeTickResponse,
    ExternalApiRequestCreate,
    ExternalApiRequestResponse,
    FiiDiiResponse,
    FnoBanListResponse,
    FnOBuildupResponse,
    FnOBuildupStock,
    FnoExpiryResponse,
    FundamentalDataResponse,
    FuturesOIResponse,
    GenericResponseSchema,
    HistoricalEquityDataResponse,
    HistoricalIndexDataResponse,
    IndexConstituentResponse,
    IndiaVIXResponse,
    InstrumentCreate,
    InstrumentResponse,
    InstrumentUpdate,
    MacroIndicatorResponse,
    MarketBreadthLiveResponse,
    MarketBreadthResponse,
    NewsCreate,
    NewsResponse,
    NewsUpdate,
    Nifty500SmaBreadthResponse,
    NseIndexResponse,
    OptionChainAnalysisResponse,
    OptionChainMetrics,
    OptionChainResponse,
    ParticipantOIResponse,
    PcrHistoryPoint,
    PositionResponse,
    RegimeLogResponse,
    SpotPriceResponse,
    StrikeDataPoint,
    SystemLogResponse,
    SystemMetricResponse,
    TaskLogSchema,
    TradeResponse,
    TradingHolidayResponse,
    TradingOrderCreate,
    TradingOrderResponse,
    TradingSignalCreate,
    TradingSignalResponse,
    WatchlistFocusResponse,
)
from .telegram import (
    TelegramChannel,
    TelegramNotifier,
    escape_html,
    send_alpha_alert,
    send_error_alert,
    send_sync_alert,
    send_telegram_alert,
)
from .time import (
    IST,
    NSE_SESSION_CLOSE,
    NSE_SESSION_OPEN,
    UTC,
    is_exchange_open,
    ist_day_bounds_utc,
    now_ist,
    sql_ist_day_range,
    to_ist,
    to_utc,
    today_ist,
    trading_day,
)
from .utils.enums import (
    BrokerNameEnum,
    BrokerTypeEnum,
    ExecutionModeEnum,
    ExecutionPlanStateEnum,
    ExitReasonEnum,
    OrderIntentEnum,
    SignalExecutionStatusEnum,
)
from .utils.fno_buildup import FNO_BUILDUP_QUERY, categorize_fno_buildup

__all__ = [
    # Version
    "__version__",
    # Enums
    "BrokerNameEnum",
    "BrokerTypeEnum",
    "ExecutionModeEnum",
    "ExecutionPlanStateEnum",
    "ExitReasonEnum",
    "OrderIntentEnum",
    "SignalExecutionStatusEnum",
    "OrderSide",
    "OrderStatus",
    "OrderType",
    "TimeInForce",
    # Broker Base
    "BrokerAdapter",
    "OrderRequest",
    "OrderResult",
    "PortfolioPosition",
    # Calendar / Trading Holidays
    "get_trading_holidays_for_year",
    "is_trading_holiday",
    # Time Utilities
    "IST",
    "NSE_SESSION_CLOSE",
    "NSE_SESSION_OPEN",
    "is_exchange_open",
    "UTC",
    "ist_day_bounds_utc",
    "now_ist",
    "sql_ist_day_range",
    "to_ist",
    "to_utc",
    "today_ist",
    "trading_day",
    # Config
    "DatabaseConfig",
    "db_settings",
    "SessionLocal",
    "get_db",
    "UpstoxApiConfig",
    # Models
    "Base",
    "BlockDeal",
    "Broker",
    "BrokerHealthLog",
    "BulkDeal",
    "Candle",
    "CorporateEvent",
    "DerivativeTick",
    "ExternalApiRequest",
    "FiiDii",
    "FnoExpiry",
    "FundamentalData",
    "FundamentalUniverse",
    "FuturesOI",
    "HistoricalEquityData",
    "HistoricalIndexData",
    "IndexConstituent",
    "Instrument",
    "MarketBreadth",
    "News",
    "NseIndex",
    "OptionChain",
    "OptionDailyMetrics",
    "Position",
    "SystemLog",
    "SystemMetric",
    "Trade",
    "TradingHoliday",
    "TradingOrder",
    "TradingSignal",
    "IndiaVIX",
    "FuturesOI",
    "ParticipantOI",
    "DeliveryData",
    "RegimeLog",
    "WatchlistFocus",
    "OptionStrategySignal",
    "OptionStrategyLeg",
    # Schemas
    "GenericResponseSchema",
    "BrokerResponse",
    "BrokerHealthLogResponse",
    "ExternalApiRequestCreate",
    "ExternalApiRequestResponse",
    "CorporateEventResponse",
    "TradingHolidayResponse",
    "HistoricalEquityDataResponse",
    "HistoricalIndexDataResponse",
    "CandleResponse",
    "OptionChainResponse",
    "OptionChainAnalysisResponse",
    "OptionChainMetrics",
    "StrikeDataPoint",
    "PcrHistoryPoint",
    "InstrumentResponse",
    "InstrumentCreate",
    "InstrumentUpdate",
    # Market Data
    "FiiDiiResponse",
    "IndiaVIXResponse",
    "FuturesOIResponse",
    "ParticipantOIResponse",
    "DeliveryDataResponse",
    "MarketBreadthResponse",
    "MarketBreadthLiveResponse",
    "Nifty500SmaBreadthResponse",
    "DerivativeMetricsResponse",
    "DerivativeTickResponse",
    "SpotPriceResponse",
    "NewsResponse",
    "NewsCreate",
    "NewsUpdate",
    "BlockDealResponse",
    "BulkDealResponse",
    "FnOBuildupStock",
    "FnOBuildupResponse",
    "MacroIndicatorResponse",
    "FundamentalDataResponse",
    "NseIndexResponse",
    "IndexConstituentResponse",
    "FnoExpiryResponse",
    "FnoBanListResponse",
    "SystemMetricResponse",
    "SystemLogResponse",
    "TaskLogSchema",
    "RegimeLogResponse",
    "WatchlistFocusResponse",
    "TradingSignalCreate",
    "TradingSignalResponse",
    "TradingOrderCreate",
    "TradingOrderResponse",
    "PositionResponse",
    "TradeResponse",
    # Request Maker
    "RequestMaker",
    "CircuitBreakerError",
    # Risk / Position Sizing
    "REGIME_RULES",
    "ATR_STOP_MULTIPLIER",
    # F&O Buildup Utilities
    "FNO_BUILDUP_QUERY",
    "categorize_fno_buildup",
    # Telegram Utilities
    "TelegramChannel",
    "TelegramNotifier",
    "escape_html",
    "send_alpha_alert",
    "send_error_alert",
    "send_sync_alert",
    "send_telegram_alert",
    # Option Greeks Utilities
    "GreeksResult",
    "calculate_greeks",
    "calculate_iv_rank",
    "calculate_iv_percentile",
    # Option Contract Resolution
    "ResolvedContract",
    "resolve_option_contract",
    # Typed Errors
    "NxTradeError",
    "DataUnavailable",
    "ExternalApiError",
    "CircuitOpen",
]
