"""Signal candidate domain dataclass."""

# stdlib
import datetime as dt
from dataclasses import dataclass, field
from typing import Any, Optional

# internal
from tb_utils.utils.enums import InstrumentTypeEnum, SignalActionEnum, TimeframeEnum


@dataclass
class SignalCandidate:
    """Represents an un-persisted signal candidate generated by a scanner."""

    symbol: str
    strategy_name: str
    strategy_type: str
    action: SignalActionEnum
    timeframe: TimeframeEnum
    entry_price: float
    target_price: float
    stop_loss: float
    confidence: float
    reason: str
    indicators: dict[str, Any] = field(default_factory=dict)
    instrument_type: InstrumentTypeEnum = InstrumentTypeEnum.STK
    strike_price: Optional[float] = None
    expiry_date: Optional[dt.date] = None
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert candidate to a plain dictionary for backwards compatibility."""
        return {
            "symbol": self.symbol,
            "strategy_name": self.strategy_name,
            "strategy_type": self.strategy_type,
            "action": self.action.value
            if isinstance(self.action, SignalActionEnum)
            else self.action,
            "timeframe": (
                self.timeframe.value
                if isinstance(self.timeframe, TimeframeEnum)
                else self.timeframe
            ),
            "entry_price": self.entry_price,
            "target_price": self.target_price,
            "stop_loss": self.stop_loss,
            "confidence": self.confidence,
            "reason": self.reason,
            "indicators": self.indicators,
            "instrument_type": (
                self.instrument_type.value
                if isinstance(self.instrument_type, InstrumentTypeEnum)
                else self.instrument_type
            ),
            "strike_price": self.strike_price,
            "expiry_date": self.expiry_date,
            "metadata": self.metadata,
        }
