"""Trading, Position, and Order Models."""

from sqlalchemy import (
    Column,
    Integer,
    String,
    Text,
    DateTime,
    Boolean,
    Numeric,
    ForeignKey,
    JSON,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from .base import Base, PostgresUpsertMixin


class TradingSignal(Base):
    """Signals generated by tb-signal-bot."""

    __tablename__ = "trading_signal"

    signal_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(Integer, ForeignKey("instrument.instrument_id"))
    strategy_name = Column(String(100), nullable=False)

    action = Column(
        ENUM("BUY", "SELL", "EXIT", name="signal_action", create_type=False),
        nullable=False,
    )
    timeframe = Column(
        ENUM(
            "SCALPING",
            "INTRADAY",
            "SWING",
            "POSITIONAL",
            name="signal_timeframe",
            create_type=False,
        ),
        nullable=False,
    )

    entry_price = Column(Numeric(14, 4), nullable=False)
    target_price = Column(Numeric(14, 4), nullable=False)
    stop_loss = Column(Numeric(14, 4), nullable=False)
    confidence = Column(Numeric(4, 3), nullable=False)
    reason = Column(Text)
    indicators = Column(JSON, default={})
    # _ suffix to avoid SQLAlchemy conflict
    metadata_ = Column("metadata", JSON, default={})
    is_executed = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now())


class TradingOrder(Base):
    """Trading Order tracking table."""

    __tablename__ = "trading_order"

    order_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(Integer, ForeignKey("instrument.instrument_id"))
    strategy_id = Column(String(50))
    broker_order_id = Column(String(50), unique=True)
    broker_id = Column(Integer, ForeignKey("broker.broker_id"))
    symbol = Column(String(20))

    side = Column(
        ENUM("BUY", "SELL", "HOLD", name="order_side", create_type=False),
        nullable=False,
    )
    order_type = Column(
        ENUM(
            "MKT",
            "LMT",
            "STP",
            "STP_LMT",
            "BRACKET",
            "TRAIL",
            name="order_type",
            create_type=False,
        ),
        nullable=False,
    )

    quantity = Column(Integer, nullable=False)
    limit_price = Column(Numeric(10, 2))
    stop_price = Column(Numeric(10, 2))
    trail_stop_price = Column(Numeric(10, 2))

    status = Column(
        ENUM(
            "NEW",
            "PENDING",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELLED",
            "REJECTED",
            name="order_status",
            create_type=False,
        ),
        nullable=False,
    )

    filled_quantity = Column(Integer, default=0)
    avg_fill_price = Column(Numeric(10, 2))
    commission = Column(Numeric(10, 2), default=0)
    parent_order_id = Column(Integer, ForeignKey("trading_order.order_id"))

    filled_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=func.now())
    updated_at = Column(
        DateTime(timezone=True), default=func.now(), onupdate=func.now()
    )

    # Relationships
    broker = relationship("Broker", back_populates="orders")
    parent_order = relationship("TradingOrder", remote_side=[order_id])


class Position(Base, PostgresUpsertMixin):
    """Current Positions table."""

    __tablename__ = "position"

    position_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(
        Integer, ForeignKey("instrument.instrument_id"), nullable=False, index=True
    )
    broker_id = Column(
        Integer, ForeignKey("broker.broker_id"), nullable=False, index=True
    )

    net_quantity = Column(Integer, nullable=False)
    average_price = Column(Numeric(10, 2), nullable=False)
    realized_pnl = Column(Numeric(10, 2), default=0)
    unrealized_pnl = Column(Numeric(10, 2), default=0)
    last_updated_at = Column(
        DateTime(timezone=True), default=func.now(), onupdate=func.now()
    )

    broker = relationship("Broker", back_populates="positions")

    __table_args__ = (
        UniqueConstraint("instrument_id", "broker_id", name="uix_position_key"),
    )


class Trade(Base):
    """Completed Trades table for performance analysis."""

    __tablename__ = "trade"

    trade_id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_id = Column(String(50), index=True)
    instrument_id = Column(
        Integer, ForeignKey("instrument.instrument_id"), nullable=False
    )
    broker_id = Column(
        Integer, ForeignKey("broker.broker_id"), nullable=False, index=True
    )

    entry_order_id = Column(Integer, ForeignKey("trading_order.order_id"))
    exit_order_id = Column(Integer, ForeignKey("trading_order.order_id"))

    side = Column(
        ENUM("BUY", "SELL", "HOLD", name="order_side", create_type=False),
        nullable=False,
    )
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Numeric(10, 2), nullable=False)
    exit_price = Column(Numeric(10, 2))
    entry_time = Column(DateTime(timezone=True), nullable=False)
    exit_time = Column(DateTime(timezone=True))

    realized_pnl = Column(Numeric(10, 2))
    commission = Column(Numeric(10, 2), default=0)
    slippage = Column(Numeric(10, 2), default=0)

    status = Column(
        ENUM("OPEN", "CLOSED", name="trade_status", create_type=False),
        default="OPEN",
        index=True,
    )

    broker = relationship("Broker", back_populates="trades")
    entry_order = relationship("TradingOrder", foreign_keys=[entry_order_id])
    exit_order = relationship("TradingOrder", foreign_keys=[exit_order_id])
