from enum import StrEnum

from sqlalchemy import (
    JSON,
    Boolean,
    Column,
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import ENUM
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from .base import Base, PostgresUpsertMixin


class StrategyClusterEnum(StrEnum):
    """Broad quantitative engine / strategy family originating the signal."""

    SHORT_TERM_CLUSTER = "SHORT_TERM_CLUSTER"
    LONG_TERM_CLUSTER = "LONG_TERM_CLUSTER"
    DELIVERY_ACCUMULATION = "DELIVERY_ACCUMULATION"
    FNO_DERIVATIVES = "FNO_DERIVATIVES"


class SignalOutcomeStatusEnum(StrEnum):
    """Lifecycle status of a trading signal."""

    ACTIVE = "ACTIVE"
    TARGET_HIT = "TARGET_HIT"
    SL_HIT = "SL_HIT"
    EXPIRED = "EXPIRED"
    INVALIDATED = "INVALIDATED"


class TradingSignal(Base):
    """Signals generated by tb-signal-bot."""

    __tablename__ = "trading_signal"

    signal_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(Integer, ForeignKey("instrument.instrument_id"), nullable=True)
    strategy_name = Column(String(100), nullable=False)
    strategy_cluster = Column(String(32), nullable=True, index=True)
    # Derivatives classification — NULL for plain equity signals
    instrument_type = Column(String(10), nullable=True)  # EQUITY, FUT, CE, PE
    strategy_type = Column(String(40), nullable=True)  # LONG_BUILDUP, PCR_REVERSAL, …
    strike_price = Column(Numeric(14, 2), nullable=True)  # options only
    expiry_date = Column(Date, nullable=True)  # futures / options

    action = Column(
        ENUM("BUY", "SELL", "EXIT", name="signal_action", create_type=False),
        nullable=False,
    )
    timeframe = Column(
        ENUM(
            "SCALPING",
            "INTRADAY",
            "SWING",
            "POSITIONAL",
            name="signal_timeframe",
            create_type=False,
        ),
        nullable=False,
    )

    entry_price = Column(Numeric(14, 4), nullable=False)
    target_price = Column(Numeric(14, 4), nullable=False)
    stop_loss = Column(Numeric(14, 4), nullable=False)
    confidence = Column(Numeric(4, 3), nullable=False)
    reason = Column(Text)
    indicators = Column(JSON, default={})
    # _ suffix to avoid SQLAlchemy conflict
    metadata_ = Column("metadata", JSON, default={})
    is_executed = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now())

    # ── Lifecycle & Outcome Verification Columns ──────────────────────────
    status = Column(
        String(20),
        nullable=False,
        default="ACTIVE",
        server_default="ACTIVE",
        index=True,
    )  # ACTIVE, TARGET_HIT, SL_HIT, EXPIRED, INVALIDATED
    exit_price = Column(Numeric(14, 4), nullable=True)
    outcome_time = Column(DateTime(timezone=True), nullable=True, index=True)
    pnl_pct = Column(Numeric(6, 3), nullable=True)
    duration_minutes = Column(Integer, nullable=True)
    duration_days = Column(Integer, nullable=True)


class TradingOrder(Base):
    """Trading Order tracking table."""

    __tablename__ = "trading_order"

    order_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(Integer, ForeignKey("instrument.instrument_id"))
    strategy_id = Column(String(50))
    broker_order_id = Column(String(50), unique=True)
    broker_id = Column(Integer, ForeignKey("broker.broker_id"))
    symbol = Column(String(60))  # widened for derivative symbols

    # ── Derivative contract columns (mirrors TradingSignal) ─────────────
    instrument_type = Column(String(10), nullable=True)  # EQUITY, FUT, CE, PE
    strike_price = Column(Numeric(14, 2), nullable=True)  # options only
    expiry_date = Column(Date, nullable=True)  # F&O only

    side = Column(
        ENUM("BUY", "SELL", "HOLD", name="order_side", create_type=False),
        nullable=False,
    )
    order_type = Column(
        ENUM(
            "MKT",
            "LMT",
            "STP",
            "STP_LMT",
            "BRACKET",
            "TRAIL",
            name="order_type",
            create_type=False,
        ),
        nullable=False,
    )

    quantity = Column(Integer, nullable=False)
    limit_price = Column(Numeric(10, 2))
    stop_price = Column(Numeric(10, 2))
    trail_stop_price = Column(Numeric(10, 2))

    status = Column(
        ENUM(
            "NEW",
            "PENDING",
            "PARTIALLY_FILLED",
            "FILLED",
            "CANCELLED",
            "REJECTED",
            name="order_status",
            create_type=False,
        ),
        nullable=False,
    )

    filled_quantity = Column(Integer, default=0)
    avg_fill_price = Column(Numeric(10, 2))
    commission = Column(Numeric(10, 2), default=0)
    parent_order_id = Column(Integer, ForeignKey("trading_order.order_id"))

    filled_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=func.now())
    updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())

    # Broker rejection/error message (populated on REJECTED status)
    error_message = Column(Text, nullable=True)

    # Product type: "D" = Delivery (CNC), "I" = Intraday (MIS)
    product = Column(String(10), nullable=True, default="D")

    # How many times this order has been handed to a broker. Incremented and
    # committed *before* the call, so an order can never be submitted twice even
    # if the process dies before the result is recorded. Order placement is not
    # idempotent: a duplicate is real money, whereas an un-sent order is
    # recoverable, so the queue must claim a row before acting on it rather than
    # after. (A missing broker_order_id previously left the row re-queueable and
    # the same GTT was sent every 30 seconds.)
    submit_attempts = Column(Integer, nullable=False, server_default="0", default=0)

    # Relationships
    broker = relationship("Broker", back_populates="orders")
    parent_order = relationship("TradingOrder", remote_side=[order_id])


class ExecutionPlan(Base):
    """Durable state machine for a single entry execution (limit → TWAP fallback).

    tb-execution used to run this inline: place a limit order, ``time.sleep(180)``
    inside the Celery task, then hand the remainder to a daemon thread that nobody
    joined. A worker restart lost the TWAP, and the sleep blocked the beat while
    holding row locks. The plan is now a row advanced one step per 15-second tick
    by ``tasks.execution_planner``, so it survives restarts and never blocks.

    Lifecycle: LIMIT_ACTIVE → (COMPLETED | TWAP_ACTIVE → COMPLETED/UNFILLED)
               with FAILED / CANCELLED as terminal error states.

    Sizing outputs (stop, target, fees) are denormalised onto the row because the
    tick that finally books the fill runs minutes after the sizer decided them.
    """

    __tablename__ = "execution_plan"

    id = Column(Integer, primary_key=True, autoincrement=True)
    symbol = Column(String(60), nullable=False)  # trading_symbol (widened for derivatives)
    instrument_id = Column(
        Integer, ForeignKey("instrument.instrument_id"), nullable=False, index=True
    )
    broker_id = Column(Integer, ForeignKey("broker.broker_id"), nullable=False)
    signal_id = Column(Integer, ForeignKey("trading_signal.signal_id"), nullable=True)
    strategy_id = Column(String(50), nullable=False)

    # ── Derivative contract columns ─────────────────────────────────────
    instrument_type = Column(String(10), nullable=True)  # EQUITY, FUT, CE, PE
    strike_price = Column(Numeric(14, 2), nullable=True)
    expiry_date = Column(Date, nullable=True)

    side = Column(
        ENUM("BUY", "SELL", "HOLD", name="order_side", create_type=False),
        nullable=False,
    )
    total_quantity = Column(Integer, nullable=False)
    limit_price = Column(Numeric(14, 4), nullable=False)

    # Sizer outputs needed when the fill is finally booked
    stop_loss_price = Column(Numeric(14, 4), nullable=False, server_default="0")
    target_price = Column(Numeric(14, 4), nullable=False, server_default="0")
    fee_round_trip = Column(Numeric(10, 2), nullable=False, server_default="0")

    state = Column(String(20), nullable=False, default="LIMIT_ACTIVE", index=True)
    # Limit stage
    entry_order_id = Column(Integer, ForeignKey("trading_order.order_id"), nullable=True)
    limit_deadline_at = Column(DateTime(timezone=True), nullable=False)
    # TWAP stage
    twap_slices_total = Column(Integer, nullable=False, server_default="0")
    twap_slices_done = Column(Integer, nullable=False, server_default="0")
    twap_remaining_qty = Column(Integer, nullable=False, server_default="0")
    next_slice_at = Column(DateTime(timezone=True), nullable=True)

    # Running fill totals (limit partial + TWAP slices)
    filled_quantity = Column(Integer, nullable=False, server_default="0")
    avg_fill_price = Column(Numeric(14, 4), nullable=False, server_default="0")
    broker_order_ids = Column(JSON, default=list)

    reason = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now(), index=True)
    updated_at = Column(
        DateTime(timezone=True), nullable=False, default=func.now(), onupdate=func.now()
    )
    completed_at = Column(DateTime(timezone=True), nullable=True)


class Position(Base, PostgresUpsertMixin):
    """Current Positions table.

    Tracks both equity and derivative (F&O) positions in a unified book.
    ``instrument_id`` always points to the underlying equity/index in the
    instrument master. Derivative-specific columns (``instrument_type``,
    ``strike_price``, ``expiry_date``) follow the same pattern as
    ``TradingSignal``. The ``trading_symbol`` is the broker-facing string
    used for order placement and reconciliation.
    """

    __tablename__ = "position"

    position_id = Column(Integer, primary_key=True, autoincrement=True)
    instrument_id = Column(
        Integer, ForeignKey("instrument.instrument_id"), nullable=False, index=True
    )
    broker_id = Column(Integer, ForeignKey("broker.broker_id"), nullable=False, index=True)

    # ── Contract identification ─────────────────────────────────────────
    trading_symbol = Column(String(60), nullable=False, index=True)
    instrument_type = Column(
        String(10), nullable=False, server_default="EQUITY", default="EQUITY"
    )  # EQUITY, FUT, CE, PE
    strike_price = Column(Numeric(14, 2), nullable=True)  # options only
    expiry_date = Column(Date, nullable=True)  # F&O only

    # ── Operational flags ───────────────────────────────────────────────
    is_algo = Column(Boolean, nullable=False, server_default="true", default=True)

    # ── Position state ──────────────────────────────────────────────────
    net_quantity = Column(Integer, nullable=False)
    average_price = Column(Numeric(10, 2), nullable=False)
    realized_pnl = Column(Numeric(10, 2), default=0)
    unrealized_pnl = Column(Numeric(10, 2), default=0)
    last_price = Column(Numeric(14, 4), nullable=True)

    # ── Audit timestamps ────────────────────────────────────────────────
    created_at = Column(
        DateTime(timezone=True), nullable=False, default=func.now(), server_default=func.now()
    )
    last_updated_at = Column(DateTime(timezone=True), default=func.now(), onupdate=func.now())

    broker = relationship("Broker", back_populates="positions")

    __table_args__ = (
        UniqueConstraint("trading_symbol", "broker_id", name="uix_position_symbol_broker"),
    )


class Trade(Base):
    """Completed Trades table for performance analysis."""

    __tablename__ = "trade"

    trade_id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_id = Column(String(50), index=True)
    instrument_id = Column(Integer, ForeignKey("instrument.instrument_id"), nullable=False)
    broker_id = Column(Integer, ForeignKey("broker.broker_id"), nullable=False, index=True)

    # ── Contract identification (mirrors Position) ──────────────────────
    trading_symbol = Column(String(60), nullable=True, index=True)
    instrument_type = Column(String(10), nullable=True)  # EQUITY, FUT, CE, PE
    strike_price = Column(Numeric(14, 2), nullable=True)
    expiry_date = Column(Date, nullable=True)

    entry_order_id = Column(Integer, ForeignKey("trading_order.order_id"))
    exit_order_id = Column(Integer, ForeignKey("trading_order.order_id"))
    stop_order_id = Column(Integer, ForeignKey("trading_order.order_id"))

    side = Column(
        ENUM("BUY", "SELL", "HOLD", name="order_side", create_type=False),
        nullable=False,
    )
    quantity = Column(Integer, nullable=False)
    entry_price = Column(Numeric(10, 2), nullable=False)
    exit_price = Column(Numeric(10, 2))
    entry_time = Column(DateTime(timezone=True), nullable=False)
    exit_time = Column(DateTime(timezone=True))

    stop_loss = Column(Numeric(10, 2))
    target = Column(Numeric(10, 2))
    realized_pnl = Column(Numeric(10, 2))
    net_pnl = Column(Numeric(10, 2))  # realized_pnl minus commission (round-trip)
    commission = Column(Numeric(10, 2), default=0)
    slippage = Column(Numeric(10, 2), default=0)

    status = Column(
        ENUM("OPEN", "CLOSED", name="trade_status", create_type=False),
        default="OPEN",
        index=True,
    )
    exit_reason = Column(String(20))  # "TARGET", "STOP_LOSS", "TRAILING_STOP", "MANUAL"

    broker = relationship("Broker", back_populates="trades")
    entry_order = relationship("TradingOrder", foreign_keys=[entry_order_id])
    exit_order = relationship("TradingOrder", foreign_keys=[exit_order_id])
    stop_order = relationship("TradingOrder", foreign_keys=[stop_order_id])


class OptionStrategySignal(Base, PostgresUpsertMixin):
    """Multi-leg option strategy generated for a directional signal (e.g. Bull Call Spread)."""

    __tablename__ = "option_strategy_signal"

    id = Column(Integer, primary_key=True, autoincrement=True)
    signal_id = Column(
        Integer,
        ForeignKey("trading_signal.signal_id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    strategy_type = Column(String(32), nullable=False)  # BULL_CALL_SPREAD, BEAR_PUT_SPREAD, etc.
    spread_type = Column(String(10), nullable=False)  # DEBIT, CREDIT
    underlying_symbol = Column(String(20), nullable=False, index=True)
    expiry_date = Column(Date, nullable=False)
    dte = Column(Integer, nullable=True)
    lot_size = Column(Integer, nullable=False, default=1)
    net_premium = Column(Numeric(10, 2), nullable=False)
    max_profit = Column(Numeric(10, 2), nullable=True)
    max_loss = Column(Numeric(10, 2), nullable=True)
    risk_reward_ratio = Column(Numeric(6, 2), nullable=True)
    breakeven_price = Column(Numeric(12, 2), nullable=True)
    underlying_entry_price = Column(Numeric(14, 4), nullable=False)
    underlying_target_price = Column(Numeric(14, 4), nullable=True)
    underlying_stop_loss = Column(Numeric(14, 4), nullable=True)
    margin_required_approx = Column(Numeric(12, 2), nullable=True)
    status = Column(
        String(20), nullable=False, default="ACTIVE"
    )  # ACTIVE, EXECUTED, EXPIRED, CLOSED
    metadata_ = Column("metadata", JSON, default={})
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now())

    legs = relationship(
        "OptionStrategyLeg",
        back_populates="strategy",
        cascade="all, delete-orphan",
        order_by="OptionStrategyLeg.execution_order",
    )
    signal = relationship("TradingSignal", foreign_keys=[signal_id])


class OptionStrategyLeg(Base, PostgresUpsertMixin):
    """Individual contract leg of a multi-leg option strategy with strict deployment sequencing."""

    __tablename__ = "option_strategy_leg"

    id = Column(Integer, primary_key=True, autoincrement=True)
    strategy_signal_id = Column(
        Integer,
        ForeignKey("option_strategy_signal.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    execution_order = Column(Integer, nullable=False)  # 1 = BUY/Hedge first, 2 = SELL short second
    action = Column(String(4), nullable=False)  # BUY, SELL
    option_type = Column(String(2), nullable=False)  # CE, PE
    strike_price = Column(Numeric(10, 2), nullable=False)
    symbol = Column(String(60), nullable=False)  # e.g. ICICIBANK 29OCT 1360 CE
    entry_premium = Column(Numeric(10, 2), nullable=False)
    target_premium = Column(Numeric(10, 2), nullable=True)
    stop_loss_premium = Column(Numeric(10, 2), nullable=True)
    delta = Column(Numeric(6, 4), nullable=True)
    theta = Column(Numeric(8, 4), nullable=True)
    iv = Column(Numeric(6, 2), nullable=True)
    open_interest = Column(Integer, nullable=True)
    volume = Column(Integer, nullable=True)
    is_hedge = Column(
        Boolean, nullable=False, default=False
    )  # True for Leg 1 BUY that unlocks margin
    created_at = Column(DateTime(timezone=True), nullable=False, default=func.now())

    strategy = relationship("OptionStrategySignal", back_populates="legs")
